// Ambient extensions to the generated `Env` type (worker-configuration.d.ts).
//
// `worker-configuration.d.ts` is regenerated by `npx wrangler types` and only
// includes fields for bindings/vars actually declared in wrangler.toml.
// Secrets (SPOTIFY_CLIENT_ID, SPOTIFY_CLIENT_SECRET, TOKEN_ENCRYPTION_KEY, ...)
// are intentionally never declared in wrangler.toml — they're set out-of-band
// via `wrangler secret put` so their real values are never committed. That
// means they never appear in the generated Env type either.
//
// This file merges the missing fields into the same ambient `Env` interface
// so the rest of the codebase can reference `env.SPOTIFY_CLIENT_ID` etc. with
// full type safety, without touching the generated file or wrangler.toml.
//
// As more secrets are introduced in later tasks (SEED_SECRET, R2_* secrets,
// RESEND_API_KEY, SENTRY_DSN, ...), add them here.
interface Env {
  SPOTIFY_CLIENT_ID: string;
  SPOTIFY_CLIENT_SECRET: string;
  GOOGLE_CLIENT_ID: string;
  GOOGLE_CLIENT_SECRET: string;
  TOKEN_ENCRYPTION_KEY: string;
  SEED_SECRET: string;
  R2_ACCOUNT_ID: string;
  R2_ACCESS_KEY_ID: string;
  R2_SECRET_ACCESS_KEY: string;
  R2_BUCKET_NAME: string;
  RESEND_API_KEY: string;
  RESEND_FROM_ADDRESS: string;
  SENTRY_DSN: string;
  // Optional pre-launch site-wide password gate (src/index.ts) -- unset
  // (the normal case once real users are live) means the gate is a no-op.
  // Set both via `wrangler secret put` to lock the whole site (API routes
  // and static pages alike, via [assets] run_worker_first) behind a single
  // shared Basic Auth prompt.
  SITE_BASIC_AUTH_USER?: string;
  SITE_BASIC_AUTH_PASSWORD?: string;
}

// `cloudflare:test`'s `env` export is typed as `Cloudflare.Env` (a separate
// ambient interface from the top-level `Env` above, both generated into
// worker-configuration.d.ts) — it needs the same merge so tests that pass
// `env` from `cloudflare:test` into `worker.fetch(req, env, ctx)` typecheck.
declare namespace Cloudflare {
  interface Env {
    SPOTIFY_CLIENT_ID: string;
    SPOTIFY_CLIENT_SECRET: string;
    GOOGLE_CLIENT_ID: string;
    GOOGLE_CLIENT_SECRET: string;
    TOKEN_ENCRYPTION_KEY: string;
    SEED_SECRET: string;
    R2_ACCOUNT_ID: string;
    R2_ACCESS_KEY_ID: string;
    R2_SECRET_ACCESS_KEY: string;
    R2_BUCKET_NAME: string;
    RESEND_API_KEY: string;
    RESEND_FROM_ADDRESS: string;
    SENTRY_DSN: string;
    SITE_BASIC_AUTH_USER?: string;
    SITE_BASIC_AUTH_PASSWORD?: string;
  }
}
